# Generated by Django 6.1a1 on 2026-06-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq1', models.TextField()),
                ('seq2', models.TextField()),
                ('energy', models.FloatField()),
                ('sequence_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='SURF2026_test.sequencelabel')),
            ],
            options={
                'indexes': [models.Index(fields=['sequence_label'], name='SURF2026_te_sequenc_233bf2_idx'), models.Index(fields=['energy'], name='SURF2026_te_energy_87b3cf_idx')],
            },
        ),
    ]
