# Generated by Django 6.1a1 on 2026-07-09 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SURF2026_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkerTemperatureCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.TextField()),
                ('target_structure', models.TextField()),
                ('validation_temperatures_C', models.JSONField()),
                ('curve', models.JSONField()),
            ],
            options={
                'db_table': 'linker_temperature_curves',
            },
        ),
        migrations.CreateModel(
            name='ValidLinkerSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle', models.TextField()),
                ('linker', models.TextField()),
                ('middle_rc', models.TextField()),
                ('linker_rc', models.TextField()),
                ('slope_kcal_per_mol_K', models.FloatField()),
                ('intercept_kcal_per_mol', models.FloatField()),
                ('curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='SURF2026_test.linkertemperaturecurve')),
            ],
            options={
                'db_table': 'valid_linker_sequences',
                'indexes': [models.Index(fields=['middle'], name='valid_linke_middle_686ee4_idx'), models.Index(fields=['linker'], name='valid_linke_linker_378e31_idx')],
            },
        ),
    ]
